config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/resume'

  devise_for :users
  resources  :posts
  resources  :projects
  resources  :contacts, only: [:new, :create]

  get 'welcome/index'
  root 'welcome#index'

  # Redirects to home_page
  get '*path' => redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "m1ndr1ft.dev@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 6)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "Yup!"
		else
			render 'new', notice: "unable to save post"
		end
	end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def edit

  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Blog post was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

	private

	def find_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image, :slug)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 6)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Project successfully saved!"
    else
      render 'new'
    end
  end

  def show
    @project = Project.friendly.find(params[:id])
  end

  def edit

  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Project was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def resume
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_intended_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Thanks for the message !</h1>

<div class="skinny_wrapper wrapper_padding message_video">
  <h2>I'll write back soon, but in the meantime... <br>
     Enjoy this classy fireplace.</h2>
  <iframe src="https://media2.giphy.com/media/ZHXz9MZbJI1YA/200.gif" width="358" height="203" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Send me a message</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name, required: true %>
		<br>
		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>
		<br>
		<%= f.label :message, "Whats up?" %><br>
		<%= f.text_area :message, as: :text %>
		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>
		<%= f.submit 'Send', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Andrey Arias - Web Dev, Engineer, Pen Tester</title>
		<!-- Google Fonts, LOL -->
		<link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
		<!-- End -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	 	<%= csrf_meta_tags %>
	</head>
	<body>
		<header id="main_navigation" class="clearfix">
			<%= link_to "<Andrey Arias/>", root_path, class: "name" %>
			<nav>
			<%= link_to "Projects", projects_path %>
			<%= link_to "Resume", static_pages_resume_path %>
			<%= link_to "Get in Touch", new_contact_path %>
			<%= link_to "Blog", posts_path %>
			<% if user_signed_in? %>
				<%= link_to "Get Out!", destroy_user_session_path, method: :delete %>
			<% end %>
			</nav>
		</header>

		<% if notice %>
			<p class="notice"><%= notice %></p>
		<% elsif alert %>
			<p class="alert"><%= alert %></p>
		<% end %>
		<nav id="main_content">
			<%= yield %>
		</nav>
		<footer id="main_footer">
			<p class="copyright">&copy;Copyright 2016, Andrey Arias</p>
			<nav>
				<i class="fa fa-envelope-o"> andreyarias.dev@gmail.com</i>
				<a href="https://www.linkedin.com/in/andreyarias" target="_blank"><i class="fa fa-linkedin"></i></a>
				<a href="https://github.com/m1ndr1ft-dev" target="_blank"><i class="fa fa-github"></i></a>
				<a href="https://twitter.com/dotdotdev" target="_blank"><i class="fa fa-twitter" ></i></a>
			</nav>
		</footer>
	</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
var disqus_config = function () {
  this.page.url = '<%= url_for([@post, {only_path: false}]) %>';
  this.page.identifier = '<%= @post.id %>';
  this.page.title = '<%= @post.title %>';
};


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//profilebloggie.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

  <!-- Error message handler -->
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
		</ul>
	<% end %>

  <!-- Form to create/edit a blog -->
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :content, "Blog here !" %><br>
  <%= f.text_area :content %>
  <br>
  <br>
  <%= f.label :image %><br>
  <%= f.file_field :image %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Blog Edit</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Blog</h1>
<div id="post_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
  <div class="post">
    <h2><%= link_to post.title, post %></h2>
    <hr>
  </div>
  <% end %>
</div>
<div class="paginate">
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1 id="page_title">Blog Template</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
 <div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
  	<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @post.content %>
  </div>
  <div id="image">
    <%= image_tag @post.image.url(:medium) %>
  </div>

  <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to 'Edit Blog', edit_post_path(@post) %>
      <%= link_to 'Delete Blog', post_path(@post), method: :delete, data: { confirm: "Delete??" } %>
    </div>
  <% end %>

  <div id="share_box">
    <p>Share my Blog</p>
    <!-- Twitter -->
   	<a onclick="javascript:window.open('https://twitter.com/share?text=<%= @post.title %> by @dotdotdev - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>

   	<!-- Facebook -->
  	<a onclick="javascript:window.open('https://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>

   	<!-- Google Plus -->
   	<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
	</div>

  <%= render 'disqus' %>

</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

  <!-- Error message handler -->
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <!-- Form to create/edit a blog -->
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  <br>
  <br>
  <%= f.label :description, "Project Description" %><br>
  <%= f.text_area :description %>
  <br>
  <%= f.label :link %><br>
  <%= f.text_field :link %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Project Edit</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects</h1>
<div id="post_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
  <div class="post">
    <p class="date"><% project.created_at.strftime('%A, %b %d') %></p>
    <h2><%= link_to project.title, project %></h2>
    <hr>
  </div>
  <% end %>
  <div class="paginate">
  <%= will_paginate @projects %>
  </div>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">Project Template</h1>
<div class="skinny_wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @project.description %>
		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
		</div>
    <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to 'Edit Project', edit_project_path(@project) %>
      <%= link_to 'Delete Project', project_path(@project), method: :delete, data: { confirm: "Delete??" } %>
    </div>
    <% end %>
  </div>
  <br>
</div>

app/views/static_pages/resume.html.erb
<div class="container">
  <div class="resume">
    <header class="page-header">
    <h1 class="page-title">Resume of Andrey Arias</h1>
    <small><i class="fa fa-clock-o"></i>Last Updated on:<time>Saturday, March 12, 2016</time></small>
    </header>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
        <div class="panel panel-default">
          <div class="panel-heading resume-heading">
            <div class="row">
              <div class="col-lg-12">
                <div class="col-xs-12 col-sm-4">
                  <figure>
                    <img class="img-circle img-responsive" alt="Hello there!" src="http://i1027.photobucket.com/albums/y337/andrey_arias/pic1_zpszkpisgra.jpg">
                  </figure>
                </div>
                <div class="col-xs-12 col-sm-8">
                  <ul class="list-group">
                    <li class="list-group-item">Andrey Arias</li>
                    <li class="list-group-item">Software Developer/Engineer</li>
                    <li class="list-group-item">Mind Matter/Freelance</li>
                    <li class="list-group-item"><i class="fa fa-phone"></i> (619) 739-3022 </li>
                    <li class="list-group-item"><i class="fa fa-envelope"></i> andreyarias35@gmail.com</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="bs-callout bs-callout-danger">
            <h4>Summary</h4>
            <li>Industries: DoD/Military/Aerospace</li>
            <li>Active DoD Clearance (exp. 2025)</li>
            <li>3 years hands-on OOP for client/server web applications experience using C/C++, Java, Python, Ruby, PHP, C#</li>
            <li>3 years of blended freelance experience developing with Ruby-On-Rails, LAMP stack and MEAN stack</li>
            <li>UI/UX: JavaScript, jQuery, HTML5, CSS3, AJAX, XML</li>
            <li>Adaptation for responsive design utilizing Bootstrap and Sass</li>
            <li>Knowledge of Shell Scripting (Bash) for automation of administrative tasks in Linux</li>
            <li>Experience building virtual Operating Systems and configuring virtual private networks utilizing VMWare workstation</li>
            <li>Experience deploying web applications to Heroku</li>
            <li>Agile/Waterfall Software Development Life Cycle</li>
            <li>Extensive experience utilizing Adobe Creative Suite (Photoshop CC, Premiere CC, After Effects CC)</li>
            <li>Creative, self-motivated, team player, pragmatic and a perfectionist</li>
            <li>Excellent communication, analytical and team building skills</li>
          </div>
          <div class="bs-callout bs-callout-danger">
            <h4>Research Interests</h4>
            <p>
              Software Engineering, Machine Learning, Artificial Intelligence,
              Penetration Testing, Reverse Engineering, Artificial Neural Networks,
              Data Science, Linux System Administration, Hacking, Android Development,
              Website Development, Nikola Tesla, Network Security, Cryptography.
            </p>
          </div>

          <div class="bs-callout bs-callout-danger">
            <h4>Prior Experiences</h4>
            <ul class="list-group">

              <!-- Most recent position -->
              <a class="list-group-item inactive-link" href="#">
                <h4 class="list-group-item-heading">Software Engineer at Vencore</h4>
                <p class="list-group-item-text"></p>
                <ul>
                  <li>
                    Continuous development of features and improvement of UI/UX for the SPAWAR / PEO C4I Integrated
                    Data Environment Repository (SPIDER).
                  </li>
                  <li>
                    Front-end UI/UX development utilizing JavaScript as well as the jQuery, Angular.js frameworks.
                  </li>
                  <li>
                    Back-end development for the C4I Advanced Planning Suite (CAPS) module utilizing C#, .NET Web
                    Forms and ASP.NET Dynamic Data leveraging Telerik Web Controls.
                  </li>
                  <li>
                    Development of database procedures and routines using Oracle SQL.
                  </li>
                  <li>
                    Provide daily task tracking via SCRUM.
                  </li>
                  <li>
                    Agile methodology maintained throughout the development cycle and sprint planning.
                  </li>
                </ul>
              </a>

              <a class="list-group-item inactive-link" href="#">
                <h4 class="list-group-item-heading">Software Engineer/Research Analyst at SPAWAR</h4>
                <p class="list-group-item-text"></p>
                <ul>
                  <li>
                    Normalize a System’s Integration database with over 51k records utilizing SQL Server and MS
                    Access.
                  </li>
                  <li>
                    Provide technical and analytical support to developers for current projects.
                  </li>
                  <li>
                    Creation of technical documentation using Adobe Acrobat Pro and Microsoft Office Suite which is
                    provided to users for use of the web application 'Work Acceptance Tool (WAT).
                  </li>
                  <li>
                    Provide daily task tracking via SCRUM.
                  </li>
                  <li>
                    Back-end development support utilizing SharePoint 2010, JavaScript and HTML.
                  </li>
                </ul>
              </a>

              <a class="list-group-item inactive-link" href="#">
                <h4 class="list-group-item-heading">Software Engineer Intern at Achieve Internet</h4>
                <p class="list-group-item-text"></p>
                <ul>
                  <li>
                    Front-End/Back-End development for creating website applications with two Content Management
                    Systems (Drupal and WordPress) utilizing HTML5, CSS3, XML, JavaScript in a LAMP Server
                    environment.
                  </li>
                  <li>
                    Provide efficient solutions for web application deficiencies and application bugs which are
                    managed and tracked via JIRA Software Development Tool.
                  </li>
                  <li>
                    Developed custom Drupal 7 modules using PHP.
                  </li>
                  <li>
                    Implementation of technical analysis through the preparation and development cycle of website
                    applications.
                  </li>
                  <li>
                    Provide daily task tracking via SCRUM.
                  </li>
                  <li>
                    Agile methodology maintained throughout project planning and development.
                  </li>
                </ul>
              </a>

            </ul>
          </div>
          <div class="bs-callout bs-callout-danger">
            <h4>Language and Platform Skills</h4>
            <ul class="list-group">
              <a class="list-group-item inactive-link" href="#">


                <div class="progress">
                  <div data-placement="top" style="width: 90%;"
                  aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">90%</span>
                    <span class="progress-type">Ruby/Ruby-on-Rails </span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 85%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="1" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">85%</span>
                    <span class="progress-type">Drupal/ Wordpress/ PHP/ Lamp Stack</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 82%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="1" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">82%</span>
                    <span class="progress-type">.NET</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 80%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="1" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">80%</span>
                    <span class="progress-type">JavaScript/ NodeJS/ MEAN Stack</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 78%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">78%</span>
                    <span class="progress-type">Android</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 75%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-success">
                    <span class="sr-only">75%</span>
                    <span class="progress-type">C/ C++/ Java</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 70%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                    <span class="sr-only">70%</span>
                    <span class="progress-type">Oracle SQL/ SQL Server/ MySQL/ SQLite/ PostgreSQL</span>
                  </div>
                </div>
                <div class="progress">
                  <div data-placement="top" style="width: 60%;" aria-valuemax="100" aria-valuemin="0" aria-valuenow="50" role="progressbar" class="progress-bar progress-bar-warning">
                    <span class="sr-only">60%</span>
                    <span class="progress-type">Python</span>
                  </div>
                </div>

                <div class="progress-meter">
                  <div style="width: 25%;" class="meter meter-left"><span class="meter-text">Learning</span></div>
                  <div style="width: 25%;" class="meter meter-left"><span class="meter-text">I'm Familiarized</span></div>
                  <div style="width: 30%;" class="meter meter-right"><span class="meter-text">I'm a guru</span></div>
                  <div style="width: 20%;" class="meter meter-right"><span class="meter-text">I''m good</span></div>
                </div>

              </a>

            </ul>
          </div>
          <div class="bs-callout bs-callout-danger">
            <h4>Education</h4>
            <table class="table table-striped table-responsive ">
              <thead>
                <tr>
                  <th>Degree</th>
                  <th>Institution</th>
                  <th>Graduation Year</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Bachelors in Computer Science and Engineering</td>
                  <td>National University</td>
                  <td class="data-centered">2015</td>
                </tr>
                <tr>
                  <td>Associates in Computer Science</td>
                  <td>Southwestern College</td>
                  <td class="data-centered">2010</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col-1 about homepage_content">
    <h2>Hello World</h2>
    <hr>
    <p>
      I am a software developer &amp; engineer living in sunny San Diego, California.
    </p>
    <p>
      I enjoy being creative and getting to learn something new every day. I also have
      a crazy entrepreneurial mind, and a crazy thirst for knowledge, that is why
      throughout the day you will find me working on many crazy development ideas
      ranging from mobile to web to software applications.
    </p>
    <p>
      On my spare time I like to be in the outdoors, spend time with my lovely wife
      and our two crazy pugs, go to the gym, spend time working as a recording
      engineer/producer in my personal recording studio, work on
      my pen test lab, and most importantly read, read, read!!!!.
    </p>
    <p>
      You can always send me a message through the link up in the nav bar to say hello
      or share any interesting stuff I may want to hear.
    </p>
  </div>
  <div class="col-2 homepage_content">
    <h2>Projects</h2>
    <hr>
    <% @projects.each do |project| %>
      <h3><%= link_to project.title, project %></h3>
      <p><small><%= project.created_at.strftime("%A, %b, %d") %></small></p>
    <% end %>
  </div>
  <div class="col-3 homepage_content">
  <h2>Blog</h2>
    <hr>
    <% @posts.each do |post| %>
      <h3><%= link_to post.title, post %></h3>
      <p><small><%= post.created_at.strftime("%A, %b, %d") %></small></p>
    <% end %>
  </div>
</div>